### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by gfokkema** [spoofax-shell/doc#1]
## documents
- [x] 19-04-2016: project plan
- [x] 29-04-2016: research report
- [x]  17-06-2016: final report
  - [x] 17-06-2016: BEP infosheet
- [ ] 01-07-2016: final presentation
## deadlines
- [x]  20-05-2016/27-05-2016: mid project meeting (coordinator + team + client)
- [x] 27-05-2016: SIG 1st submission
- [x] 17-06-2016: SIG 2nd submission
# TODO list
- [x] propose a project and register it on BEPSys
- [x] get name of TU coach from Eelco
- [x] invite TU coach via BEPsys
- [x] final approval coordinator
- [ ] sign license agreement
## Practical issues:
- [x] organize Trello board
- [x] communicate to Eelco:
  - [x] Trello board
  - [x] TU attendance (presence from Tuesday onwards?)
- [x] Metaborg GitHub organization?
  - [x] PR-based development?
  - [x] private forks?
  - [x] SCRUM? (imo yes, since it's the only model we've learned)
## Orienting research:
- [x] exploring spoofax; users and developers perspective
- [x] tooling spoofax; do testing frameworks exist?
- [x] action plan
- [x] orienting research
# timeline:
- ~~need-to-meet (weekly?) meetings with coach~~
  - ~~prepare meetings~~
  - ~~send documents to be discussed beforehand~~
- ~~make sure coach and client are available on 01-07-2016~~
