### ISSUE TITLE
Final report consistency checklist

### ISSUE THREAD

**Issue by Hjdskes** [spoofax-shell/doc#49]
- [x] Use present tense instead of future tense when describing the contents of a chapter or (sub)section -- e.g., "This section describes" vs. "This section will describe"
- [x] Proper American English -- e.g., verify all `-lled` are correct, `-ior` instead of `iour`, `-zed` instead of `-sed`
- [x] Write out small numbers
- [x] Refer to other parts as either chapter or section -- not subsection or subsubsection or paragraphs.
- [x] Make sure all references work.
- [x] When citing, it should be "Foo~et~al." when referring to a publication by three or more people. Not "et. al.", and not "et al"
- [x] When citing, do not use e.g. "as seen in~\cite{...}" because this looks weird: "as seen in [10]"
- [x] Non-breakable space before each `\cite` and `\ref` (preferably use `\cref`).
- [x] Do not (see what I did there?) use constractions (`grep -R "n't" *` and `grep -R "'ll" *` `grep -R "'re" *`)
- [x] Do not use "we" and "our"
- [x] Consistent camelcasing of (sub)sections
- [x] Every chapter and section (and subsection?) has an introduction (and a conclusion?). See feedback Hendrik.
- [x] Be careful when using "all languages defined in Spoofax" (see feedback Hendrik)
- [x] When quoting something, use `` and ''.
- [x] Do not use superlatives.
- [x] When introducing classes, use `` and ''. Afterwards, just `\texttt`
- [x] `DynSem`, not `Dynsem` or `dynsem`.
- [x] Remove conjuctive hyphenation.
- [x] Resolve TODOs
- [x] Resolve FIXMEs.

Feel free to add more to the list.

**Comment by Hjdskes** [comment]
~~Also open all the files in a tex editor with spell checking to catch typos.~~

**Comment by Unia** [comment]
Look for TODOs and FIXMEs.
